from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field


# 1. Deterministic Data Schemas (Sourced directly from User/Birth profiles)
class PersonaIdentity(BaseModel):
    name: str
    preferred_language: str
    timezone: str
    life_stage: Optional[str] = None


class PersonaLifeContext(BaseModel):
    primary_concern: Optional[str] = None
    faith_level: Optional[str] = None
    tradition: Optional[str] = None


class PersonaSpiritualConnection(BaseModel):
    deities: List[str] = Field(default_factory=list)
    current_practices: List[str] = Field(default_factory=list)
    daily_time_minutes: int = 10


class PersonaVedicProfile(BaseModel):
    rashi_name: Optional[str] = None
    ruling_planet: Optional[str] = None
    nakshatra_name: Optional[str] = None
    # ... other deterministic panchang fields can be added as needed


# 2. LLM-Generated Insights Schema (Generated by Gemini)
class DeityPractice(BaseModel):
    deity_name: str
    suggested_mantra: str
    puja_routine: str
    devotional_habits: List[str]


class AstrologicalTraits(BaseModel):
    rashi_characteristics: str
    strengths: List[str]
    karmic_focus: str  # e.g., what they should work on


class SakhaPersona(BaseModel):
    communication_style: str
    preferred_tone: str
    guidance_style: List[str]
    topics_to_emphasize: List[str]


class LLMGeneratedInsights(BaseModel):
    sakha_persona: SakhaPersona
    deity_practices: List[DeityPractice] = Field(
        description="Specific practices tailored to the user's chosen deities (e.g. Shiva)"
    )
    astrological_traits: Optional[AstrologicalTraits] = Field(
        default=None,
        description="Personalized characteristics derived from their Rashi and Nakshatra"
    )
    recommended_daily_habits: List[str] = Field(
        description="General good habits for spiritual growth"
    )


# 3. The Canonical Persona Schema
class CanonicalPersonaSchema(BaseModel):
    persona_version: str = "1.1"
    generated_at: str
    
    # Deterministic blocks
    identity: PersonaIdentity
    life_context: PersonaLifeContext
    spiritual_connection: PersonaSpiritualConnection
    vedic_profile: PersonaVedicProfile
    
    # AI Generated block
    ai_insights: LLMGeneratedInsights


# 4. Updated Response Models
class PersonaResponse(BaseModel):
    user_id: str
    persona_version: str = "1.1"
    completeness_level: int = 2
    canonical_persona: CanonicalPersonaSchema


class PersonaGenerateRequest(BaseModel):
    force_refresh: bool = False
